import Head from 'next/head'
import { useRouter } from 'next/router'
import { useEffect } from 'react';

export default function Home() {
  const router = useRouter();



useEffect(() => {
  const token = localStorage.getItem('token')
  if(!token){
    router.push('/Authenticate/Login')

  }else{
   console.log("token exist")
  }
}, [])


  return (
    <>
      <Head>
        <title>CRM Billing System</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className='container bg-white flex items-center justify-center h-screen'>
        <div className='font-extrabold text-4xl text-purple-600'>
          Welcome to Our Customer Relation Management System!
        </div>
      </section>
      
     
    </>
  )
}
